{
    "id": "CVE-2025-57833",
    "product": "Django",
    "version": "4.2 ",
    "vulnerability": [
        "CWE-89 Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')"
    ],
    "description": "An issue was discovered in Django 4.2 before 4.2.24, 5.1 before 5.1.12, and 5.2 before 5.2.6. FilteredRelation is subject to SQL injection in column aliases, using a suitably crafted dictionary, with dictionary expansion, as the **kwargs passed QuerySet.annotate() or QuerySet.alias().",
    "poc": {
        "reference": [
            "No PoCs from references."
        ],
        "github": [
            "https://github.com/ARPSyndicate/cve-scores",
            "https://github.com/EyalSec/EyalSec_CVE",
            "https://github.com/Mkway/CVE-2025-57833",
            "https://github.com/PuddinCat/GithubRepoSpider",
            "https://github.com/loic-houchi/Django-faille-CVE-2025-57833_test",
            "https://github.com/nomi-sec/PoC-in-GitHub",
            "https://github.com/thexnumb/thexwriteup"
        ]
    }
}