{
    "id": "CVE-2025-4515",
    "product": "PrivateGPT",
    "version": "0.6.0 ",
    "vulnerability": [
        "Origin Validation Error",
        "Permissive Cross-domain Policy with Untrusted Domains"
    ],
    "description": "A vulnerability, which was classified as problematic, was found in Zylon PrivateGPT up to 0.6.2. This affects an unknown part of the file settings.yaml. The manipulation of the argument allow_origins leads to permissive cross-domain policy with untrusted domains. It is possible to initiate the attack remotely. The exploit has been disclosed to the public and may be used. The vendor was contacted early about this disclosure but did not respond in any way.\nEs wurde eine problematische Schwachstelle in Zylon PrivateGPT bis 0.6.2 gefunden. Es betrifft eine unbekannte Funktion der Datei settings.yaml. Durch Manipulation des Arguments allow_origins mit unbekannten Daten kann eine permissive cross-domain policy with untrusted domains-Schwachstelle ausgenutzt werden. Der Angriff kann \u00fcber das Netzwerk erfolgen. Der Exploit steht zur \u00f6ffentlichen Verf\u00fcgung.",
    "poc": {
        "reference": [
            "https://gist.github.com/superboy-zjc/2a727cb0c1d468f21a91e0416d006ffe"
        ],
        "github": [
            "No PoCs found on GitHub currently."
        ]
    }
}