{
    "id": "CVE-2023-1436",
    "product": "jettison",
    "version": "0< 1.5.4 ",
    "vulnerability": [
        "CWE-674 Uncontrolled Recursion"
    ],
    "description": "An infinite recursion is triggered in Jettison when constructing a JSONArray from a Collection that contains a self-reference in one of its elements. This leads to a StackOverflowError exception being thrown.",
    "poc": {
        "reference": [
            "https://research.jfrog.com/vulnerabilities/jettison-json-array-dos-xray-427911/"
        ],
        "github": [
            "No PoCs found on GitHub currently."
        ]
    }
}