{"id": "CVE-2018-16438", "product": "n/a", "version": "n/a", "vulnerability": ["n/a"], "description": "An issue was discovered in the HDF HDF5 1.8.20 library. There is an out of bounds read in H5L_extern_query at H5Lexternal.c.", "poc": {"reference": ["https://github.com/TeamSeri0us/pocs/tree/master/hdf5/h5stat"], "github": ["No PoCs found on GitHub currently."]}}