{
    "id": "CVE-2017-5992",
    "product": "n/a",
    "version": "n/a",
    "vulnerability": [
        "n/a"
    ],
    "description": "Openpyxl 2.4.1 resolves external entities by default, which allows remote attackers to conduct XXE attacks via a crafted .xlsx document.",
    "poc": {
        "reference": [
            "https://bitbucket.org/openpyxl/openpyxl/commits/3b4905f428e1",
            "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854442"
        ],
        "github": [
            "No PoCs found on GitHub currently."
        ]
    }
}