{
    "id": "CVE-2019-20428",
    "product": "n/a",
    "version": "n/a",
    "vulnerability": [
        "n/a"
    ],
    "description": "In the Lustre file system before 2.12.3, the ptlrpc module has an out-of-bounds read and panic due to the lack of validation for specific fields of packets sent by a client. The ldl_request_cancel function mishandles a large lock_count parameter.",
    "poc": {
        "reference": [
            "http://lustre.org/"
        ],
        "github": [
            "No PoCs found on GitHub currently."
        ]
    }
}