{"id": "CVE-2019-20426", "product": "n/a", "version": "n/a", "vulnerability": ["n/a"], "description": "In the Lustre file system before 2.12.3, the ptlrpc module has an out-of-bounds access and panic due to the lack of validation for specific fields of packets sent by a client. In the function ldlm_cancel_hpreq_check, there is no lock_count bounds check.", "poc": {"reference": ["http://lustre.org/"], "github": ["No PoCs found on GitHub currently."]}}