{
    "id": "CVE-2020-8192",
    "product": "fastify",
    "version": "n/a",
    "vulnerability": [
        "Denial of Service (CWE-400)"
    ],
    "description": "A denial of service vulnerability exists in Fastify v2.14.1 and v3.0.0-rc.4 that allows a malicious user to trigger resource exhaustion (when the allErrors option is used) with specially crafted schemas.",
    "poc": {
        "reference": [
            "https://hackerone.com/reports/903521"
        ],
        "github": [
            "https://github.com/ossf-cve-benchmark/CVE-2020-8192"
        ]
    }
}