{
    "id": "CVE-2021-32285",
    "product": "n/a",
    "version": "n/a",
    "vulnerability": [
        "n/a"
    ],
    "description": "An issue was discovered in gravity through 0.8.1. A NULL pointer dereference exists in the function list_iterator_next() located in gravity_core.c. It allows an attacker to cause Denial of Service.",
    "poc": {
        "reference": [
            "https://github.com/marcobambini/gravity/issues/319"
        ],
        "github": [
            "No PoCs found on GitHub currently."
        ]
    }
}